linux:
	clang++ main.cpp script/*.cpp -o main -lsfml-graphics -lsfml-window -lsfml-system

linuxbrew:
	clang++ main.cpp script/*.cpp -o main -I /home/linuxbrew/.linuxbrew/include -L /home/linuxbrew/.linuxbrew/lib -lsfml-graphics -lsfml-window -lsfml-system -rpath /home/linuxbrew/.linuxbrew/lib	
